#include <stdio.h>
#include "udp.h"
#include "mfs.h"

#define BUFFER_SIZE (1000)

char tester[4096] = "STARTRaaMwkvUhkzbALgzvJLtjhBybChxAjrzEbjWaapPnyrfqLKNSaDvGuxvtardAqmdKgpfeKaducqMAXPwYKdUBApgqkPEvTwtXXqFwNwnZcDiPYhBaSgwjUZqtYGiYgnMSyqyyHpVwAdYpAHcHAjDwRxhaHhjqJbiNtMakPUNHzTWLatnZHjAYFJwnQekGZLrEpENGNxxCmVaxnUWwkQxfUfJTtkmZepVErKwemEiZyYizZRAaewJkdPHPtKZBLytYQvxeAgbCUCNDnZYAiWztPMmgrWufmZvQDXGardBMqxkMgiMdPukWPhztHxACTxdMECGQGLhqZRwEvDFeiPBEdLNbVxKNdzVWvyFGBqnxGdCMiEgHjyazAaVLATeLuEHbLzAXpGuBvhCVExepVDDAVuwUtMqTELDkEjLTAZPrEQhPPvqHSXaBwCMABqxkuyAdRmJkhbKebWhAemKrxRTMhnJkXbrKPizNCPjMFmwyWDZViuUSqPWQxECgpKQehMRVLvexUTBcAcxnanpyDkDcuPteXFJayzJxZZRfpErAmdkHRxmdthNWKGwXYNdbRruiLCQxBUCibzFSazFuSYfbUndgTZEpJkeiUbguwSKfPZiBwTQXLGjFDVKjduqNiCfMtzfdxzQRTePYFSkfRtRVgFRbWBkAfjtKJzTSJKbThCzBQTbcDMSdTEAWGMiLGYbuSrYQETNnuWAcpDeSxbwVCVySTFZGmwpyBzwzhgbxacRJnyUYkiJnUqcJESPhWTxacquTfeNLfKAXPjyYkAXWTMCAGSAmtqbdTWWiuCEhMGFufiyiRtuBULiHSHUmSVvikZrgmQVmcEdByDmyxKNiMCSiVUXyEuSwVTgdcvpbXNeevKWKnehGJZvaBaqzyLPFNLAzQRfaVRGARRFyxJtYgLSyYHwvjMLGVNgbCvWwtuXwZUpXDnbEiUCmxzWNAFAWGRSfTffynexdUMFABTuVnyBgLxpwkwHxxcGmGmukBnTrcfvLHrcByGSauFxVkgRGNXLprnebrPPLAKFBHpFRBWbAgeRGXNhLxAEmFtXYfrigVjHiATeMxuFRyMthThHMBQjnRetUFaDdbpjPFWGnMCSdYeVWyiDPFmVmdvMCRjgmvTvWtfJqdQWbDDepRwBBfuZpEGFqKEkUrknzBMEATrHhZvjdvxiDcYXRKQwPTYgCNHewkgKqdYwZNDEUNSXebFQiZbkprCEiAQgQGrretKuNSVnPZNDVurMPFDRAzFMGDvBWEJqReAUYhbDGEYRAxjgGeJRGHfaCiagKwHquEQKcqgkvGCRtTaBvBUkjRieSMyBMQPuVKXAggeDPuAYSxrgKRGFDjvjWUryfJecMjcWyGmPnbMSKMCEpcrkHYaNNJdwfPaLQZQfFCiiyrbSPuznPFXrVmgmiZVzUiebnFNRNQSzJzYbnbLgaQMkcYkgwTeVMeeUdNwpExbxxBEptvgkLcWDCVgmezjdLPauBtjEFhMDrHWpUrrTkacmUZxVGGvLZARyZnSDzJiMmMZnCjajRrGbLEjwhGQSyBbxNhcQSiYjjWMvReAwEtnHkcnWYmDQEfYLWUpYTYvGVYAakEmRKLqUjRXBDbQLXXPCkZmHjyBXWBitQpxCLpBiguZGYcYjgVPiqtEjcJZRVqbfBCYMJmmdrmAxfpaevtCemydHtVuPLRAWGnRPtHzAumdZBySnnjZffKihJrxhKRkXUiErwbUWvLvzguBdDeWLYyMxkAUHMhiQSUwifEqEtXyBGZUKGZackSLTRPDEgfQLJAhkfjLVhqnPkznKgVPAZXLrdNJPtcnVdyBaAmaaJpnPzudakxfacRwfRWScKyFmwpmyztQvjHKTddWLmLYpDUuvnMMvNTRBqZkrJbwDYdcWEAdrPELwxqtEcWCenYXUxdbFvyFyAnUArKVdECvydzEaKHPhNcGKKSzjLiEmLjvKZZBrpLRQYzGqbZScYqAqRNSdEYnVytLBaQnkaASMTVAJXmTgVUrKLtMGPzENDPhhviNLhUtMYPDwfwqeSFbKfKrHAFZeRHyEvXLqmuqzVgFmhQpcCMBkbtFWAzkLAYfVYNurFeWEeehuADRzLhxgQyvahHuEWYCgLjYEaygbKikETAeCQVCHcaeqZXFJHPrzVfBeeLrdhnGJXRZmgGnjkZnANwPfBPbeeKVpYUmivgVcCtvHcwnVkYzhrrmnHymbTurJJAPrvYyFRVXRSVBRjUXNNkAmAVQSgbyGEXxywUCSfzteKZwHvBCLDyUqtSpmYfibdtYJeLKtGARANSrNQCXRZjbKXwuXRdwzBXYgKBgtgkMzRqBzWcbJEUjUgPJafzwZWLAQLYXtgzRLQDuurkMxKZUKBdZQaAmKeNmVAccHjkSFaZFvkGETYCtWKBjKYinGevEWYHfhmcknpzaVmTGWqCetLPECGYuZpQcTnRUzLKwRYntiikCWpJWjCRMNRcBnENbXLNAmHVnMtwTxHjHfXXrGBBRAwpJpnveHWhiLTNhqXxJaKhqJVTZmYyLDJhFPWukhSDCmhnBTPizgEXYwJgkVyjaQEaQinRhPewmkGhNJxXqRkMUnZaiqCfWAJirCRWVrunLTEvVtjvBHrJFAQahrThxWMrdfRUarFArRrCfUABgGApPQiVjhKBJChHqJexjfrmDczDxxkWpzxHqHakwktuZgGEmmXaDwXxZyfLMBMXfTcqwyLWfYTpPWJwbHuZwnFKmiLUVcdYHAQrhyCgqeakqpfxReFZBYUuvuXXgtFrQyELTwUizWcKGthigytrBjahpmxpQzNacRKcVDiApUWkXCEjRzyZHKTPQENamgNQFmQJHRwxRkVnyZiWXaxDQTgervjiPZEjpeuFXHjGBGmAByAcrZVWuXgYjFZbtWGSLVYVMizPvyuYAynzkRedwBJBEquVgeeuNMqwdeTuPASfjyiRBaUSdzjHijcWfxtMBTKYpQcVawWwMpddyXVRhEHmDazrwpQWWaaPWHdySdYtmLxmQBndwceTymtCMwhxFxxpUqwNGQphaZekbnrnHqBVkQxnuVtKbuwJFxuMCMLqcRBvZubLxxyJyzKbacWEvPBpHCZjBJNkjuwuTqKEEeApXkNVnYcTExDYKUqwNxqcyEYhbYaCiyPnGyegHqxVxRadUxRkBPYRhqYdngtpGTTzJgmQHTSKQQgczqQhjbcYcvfrVxVYRUypqQdjBUVLPerfWzMhvnbpituFNyjEYfyGtfTyWyUtFbxftZNiKiSiwVDpPccckmSfdqFdEcwddEgLMbudNuuuyaqBCZFthYCjvPRJZeVGMrDPmCcSxiGjBiTHVmhGRXXyUSxZgEkanECUzcNbUqupBRQYhacgBFkyeSTcNDgnBuZBqjWhgjgzGFBaREkndMNreEPQnCqwCETpxLNmHgNihPJZRwBerveBaqwqVWiDxrbiDWYrMHbKDeAWmeBDZcWQkWpkGKmwRXyxxnCZcHEBxgdYfvcprVSKnzTXmhUUkgBYMTjTRkzRSrjfheqErPaDCPqTtXpBmyjWyyUueybXhrwqqBXNxHKJuvKSVCccJHSCwzhDminhgQyiKujWreSJHWajjtugxVUeLdNHeKqKFaZRMjpLugxQEvLYvvLEyDPhNzTNHdTCiCUxuePVdvbgjETSBYMnjGQjEWThNhtufjbxcpdqcwxWxenRpFMDTvcDHBPzZafjJKcVVnCyqQGiGDDnaKcFSpnhmWZKGBmvSZRUTRhMuuCnykvTHYXMufrjctwPTxaANTjgcZKcwWLxBdYfiJYhSdbfhUvheJrujkcapBzpBYZZQuVZCwhBmqrVzJcuXZFgVRDcNnRcdPfCPDxQXzvBvmyXzGJpCPTmeVCYRHpeHCRrvHKwvPbGyhMhqKNMkaLDSYifEnAFbXJiPMbfGpjmyiwNdkPJKQrLDTqdVUjVtAqzYpJdvWhLZrpEZKDdpLSdmPhLxBxRpRewegRaMUgjZkVmzmQAnnQGMLNACAjDxzDZhUphFCnFmnWvBCtFSbvpAtbHYhuuWBkKKDJyudfqtddyaRYCEZhdMRDKqjeDXcFINISH";

int sd;
// client code
int main(int argc, char *argv[])
{
    // struct sockaddr_in addrSnd, addrRcv;

    // int sd = UDP_Open(20000);
    // int rc = UDP_FillSockAddr(&addrSnd, "localhost", 10003);

    char message[BUFFER_SIZE];
    sprintf(message, "hello world");

    sd = MFS_Init("localhost", 72727);

    // MFS_Lookup(0, ".");
    // MFS_Lookup(0, "..");

    printf("%d\n", MFS_Creat(0, MFS_REGULAR_FILE, "a"));

    int inum = MFS_Lookup(0, "a");

    printf("%d\n", MFS_Write(inum, tester, 0, MFS_BLOCK_SIZE));

    //printf("%d\n", MFS_Write(1, "game", 27, 28));
    char *buf = malloc(MFS_BLOCK_SIZE);
    printf("%d\n", MFS_Read(inum, buf, 0, MFS_BLOCK_SIZE));
    printf("string at buf is %s\n", buf);
    // printf("%d\n", MFS_Read(1, buf, 27, 28));
    // printf("string at buf is %s\n", buf);
    free(buf);
    //printf("%d\n", MFS_Lookup(3, "d"));

    MFS_Shutdown();
    return 0;
}
